project:
  type: website
  output-dir: docs
  resources:
    - icons/

website:
  title: "Retail Data"
  sidebar:
    style: "docked"
    contents:
      - text: "<span id='sidebar-title'>Pages</span>"
      - href: categories.qmd
        text: "<span class='sidebar-icon' style='--icon: url(/Retail_Data/icons/categories.svg)'></span>Categories"
      - href: products.qmd
        text: "<span class='sidebar-icon' style='--icon: url(/Retail_Data//icons/products.svg)'></span>Products"
      - href: customers.qmd
        text: "<span class='sidebar-icon' style='--icon: url(/Retail_Data/icons/customers.svg)'></span>Customers"
      - href: orders.qmd
        text: "<span class='sidebar-icon' style='--icon: url(/Retail_Data/icons/orders.svg)'></span>Orders"
      - href: details.qmd
        text: "<span class='sidebar-icon' style='--icon: url(/Retail_Data/icons/order_details.svg)'></span>Order Details"

  navbar:
    search: true
    pinned: true
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: "https://github.com/theppel/Retail_Data"

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    page-layout: full